### PR TITLE
Update git-pr

### PR DESCRIPTION
**Pull request by benjaoming**
So you don't have to cd manually back to previous working dir :)

### CODE REVIEW

**Comment by jamalex** [comment]
Interesting! I guess that's needed because of something in how zsh works? In bash, for me, it auto-returns me to the original working directory. This should be ok for bash too, though.

**Comment by jamalex** [comment]
Haha, post-merge assignment. WHAT WOULD YOU HAVE ME DOOOO, @aronasorman??? :laughing:

**Comment by benjaoming** [comment]
@jamalex it returns? From the scripting, it seems you know more Bash than I do :) I just remember doing all these bash scripts a year ago and having to use `cd -` all the time because it to the shell's working dir weird places... I have solved a non-issue :-1:

**Comment by jamalex** [comment]
For me it does, at least -- not sure if it's universal. E.g.:

```
jamalex@ace:~/fle/ansible-playbooks$ git pr
Counting objects: 27, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (15/15), done.
Writing objects: 100% (17/17), 20.51 KiB | 0 bytes/s, done.
Total 17 (delta 6), reused 0 (delta 0)
To git@github.com:jamalex/ansible-playbooks.git
   661f277..551d024  master -> master
Created new window in existing browser session.
jamalex@ace:~/fle/ansible-playbooks$ 
```

**Comment by benjaoming** [comment]
Yeah I did tests in bash and zsh and it's a non-issue :) so no need really

**Comment by jamalex** [comment]
Windows, on the other hand... 
https://github.com/learningequality/ka-lite/blob/e360e22318bd644223110b6225ce6566b8b23b4b/scripts/cronstop.bat

**Comment by benjaoming** [comment]
LOLdows :D

**Pull request merged**
